proman/urls.py
from django.conf.urls import url
from . import views

app_name = 'proman'
urlpatterns = [
    url(r'^$', views.index, name='index'),

    url(r'^wiadomosc/wyslij/$', views.message_send, name='message_send'),
    url(r'^wiadomosci/$', views.message_show, name='message_show'),
    url(r'^wiadomosci/(?P<friend_id>[0-9]+)/$', views.message_show, name='message_show'),

    url(r'^profile/(?P<user_id>[0-9]+)/$', views.user_profile, name='user_profile'),

    url(r'^projekty/$', views.projects, name='projects'),
    url(r'^projekty/edytuj/(?P<project_id>[0-9]+)/$', views.project_edit, name='project_edit'),
    url(r'^projekty/usun/(?P<project_id>[0-9]+)/$', views.project_remove, name='project_remove'),
    url(r'^projekty/przegladaj/(?P<project_id>[0-9]+)/$', views.project_show, name='project_show'),
    url(r'^projekty/dodaj/$', views.project_add, name='project_add'),

    url(r'^projekty/dolacz/$', views.project_join, name='project_join'),  # form with Access Code. User joins himself
    url(r'^projekty/dolacz/(?P<project_id>[0-9]+)/$',
        views.project_add_member, name='project_add_member'),  # owner joins others
    url(r'^projekty/dolacz/(?P<project_id>[0-9]+)/(?P<member_id>[0-9]*)/$',
        views.project_add_member, name='project_add_member'),  # owner joins others
    url(r'^projekty/odlacz/(?P<project_id>[0-9]+)/(?P<member_id>[0-9]+)/$',
        views.project_del_member, name='project_del_member'),
    url(r'^projekty/wagi/(?P<project_id>[0-9]+)/$', views.task_change_weight, name='task_change_weight'),

    url(r'^zadania/$', views.tasks, name='tasks'),
    url(r'^zadanie/przegladaj/(?P<task_id>[0-9]+)/$', views.task_show, name="task_show"),
    url(r'^zadanie/dodaj/(?P<project_id>[0-9]+)/$', views.task_add, name="task_add"),
    url(r'^zadanie/usun/(?P<task_id>[0-9]+)/$', views.task_remove, name='task_remove'),
    url(r'^zadanie/edytuj/(?P<task_id>[0-9]+)/$', views.task_edit, name='task_edit'),
    url(r'^zadanie/zrobione/(?P<task_id>[0-9]+)/$', views.task_done, name='task_done'),

]

shoutbox/urls.py
from django.conf.urls import url
from . import views

app_name = 'shoutbox'
urlpatterns = [
    url(r'^$', views.index, name='index'),
]

simpleprojectmanager/urls.py
from django.conf.urls import url, include
from django.contrib import admin
# from django.views.static import serve

urlpatterns = [
    url(r'^', include('proman.urls'), name='proman'),
    url(r'^login/', include('login_app.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^czat/', include('shoutbox.urls'), name='shoutbox'),
    # url(r'^static/', serve),
]

proman/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.contrib.auth.models import User

from django.template.defaultfilters import truncatechars
from django.core.validators import MaxValueValidator, MinValueValidator

from django.utils import timezone

class Project(models.Model):
    name = models.CharField(max_length=80, verbose_name="nazwa projektu")
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Właściciel")
    startdate = models.DateField(verbose_name="Data rozpoczęcia")  # auto_now_add=True
    enddate = models.DateField(verbose_name="Data zakończenia")
    passforjoin = models.CharField(max_length=80)
    complete_proc = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(100)],
                                        verbose_name="procent wykonania projektu")

    def __str__(self):
        return self.name

    def refresh_complete_proc(self, taskslist):
        level = 0
        for task in taskslist:
            level += (task.weight / 100) * task.complete_proc
        self.complete_proc = level
        if self.complete_proc == 100:
            self.enddate = timezone.now()
        self.save()

    @staticmethod
    def live_projects(user):
        return list(Project.objects.filter(owner=user, complete_proc__lt=100)) + \
                    [i.project for i in user.team_set.all() if i.project.complete_proc < 100]

    @staticmethod
    def end_projects(user):
        return list(Project.objects.filter(owner=user, complete_proc__exact=100)) + \
                   [i.project for i in user.team_set.all() if i.project.complete_proc == 100]

    class Meta:
        verbose_name_plural = "projekty"
        ordering = ['enddate']


class Team(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE, verbose_name="projekt")
    member = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="członek")

    def __str__(self):
        return "Projekt: " + self.project.name + " User: " + self.member.username

    class Meta:
        verbose_name_plural = "zespoły"


class Task(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE, verbose_name="nazwa projektu")
    name = models.CharField(max_length=80, verbose_name="nazwa zadania", default="zadanie")
    description = models.TextField(verbose_name="treść")
    contractor = models.ForeignKey(User, verbose_name="wykonawca", db_column='member')
    weight = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(100)],
                               verbose_name="waga zadania")
    complete_proc = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(100)],
                                        verbose_name="procent wykonania zadania")
    create_date = models.DateField(verbose_name="Data utworzenia", default=timezone.now)

    def __str__(self):
        return self.name

    @property
    def short_description(self):
        return truncatechars(self.description, 100)

    class Meta:
        verbose_name_plural = "zadania"
        verbose_name = "zadanie"

proman/forms.py
# coding=utf-8
from django import forms
from .models import Project, Task
from django.contrib.auth.models import User


class ProjectAddForm(forms.ModelForm):
    startdate = forms.DateField(widget=forms.DateInput(attrs={'class': 'datepicker'}), label="Data rozpoczęcia")
    enddate = forms.DateField(widget=forms.DateInput(attrs={'class': 'datepicker'}), label="Data zakończenia")

    class Meta:
        model = Project
        fields = ['name', 'startdate', 'enddate']

class ProjectJoinForm(forms.Form):
    passforjoin = forms.CharField(required=True, label="Kod dostępu")

class MessageForm(forms.Form):
    recipient = forms.ModelChoiceField(required=True, queryset=User.objects.all(), label="Odbiorca")
    content = forms.CharField(widget=forms.Textarea, required=True, label="Treść")


class TaskCompleteProcentForm(forms.Form):
    task_progress = forms.IntegerField(label="Wykonano", min_value=0, max_value=100)


class TaskAddForm(forms.ModelForm):
    contractor = forms.ModelChoiceField(queryset=User.objects.all(), label="Wykonawca")

    def __init__(self, *args, **kwargs):
        users = kwargs.pop('users')  # pop must be before super method
        super(TaskAddForm, self).__init__(*args, **kwargs)
        self.fields['contractor'].queryset = users

    class Meta:
        model = Task
        fields = ('name', 'description', 'contractor')

class TaskWeightForm(forms.ModelForm):
    weight = forms.IntegerField(min_value=0, max_value=100,)

    def __init__(self, *args, **kwargs):
        txt = kwargs.pop('txt')
        super(TaskWeightForm, self).__init__(*args, **kwargs)
        self.fields['weight'].label = txt

    class Meta:
        model = Task
        fields = ['weight']

proman/views.py
# coding=utf-8
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseForbidden

from django.contrib.auth.models import User
from .models import Project, Team, Task
from .forms import ProjectAddForm, ProjectJoinForm, MessageForm,\
    TaskCompleteProcentForm, TaskAddForm, TaskWeightForm
from django.contrib.auth.forms import PasswordChangeForm

from directmessages.apps import Inbox
from directmessages.models import Message

from django.contrib.auth.hashers import check_password
from django.contrib.auth import update_session_auth_hash

from django.db.models.functions import TruncMonth
from django.db.models import Count


"""
Auxiliary function
"""
def get_count(tas, month_num):
    for t in tas:
        if t["month"].month == month_num:
            return t["c"]
    return 0

def month_order(tas):
    names = [
                "styczeń","luty","marzec","kwiecień","maj","czerwiec","lipiec","sierpień","wrzesień",
                "październik","listopad","grudzień"
             ]
    ordered = []
    for i in range(1,13):
        ordered.append([names[i-1], get_count(tas, i)])

    return ordered

"""
Main page with overview
"""
@login_required(login_url='/login/')
def index(request):
    live_projects_count = len(Project.live_projects(request.user))
    end_projects_count = len(Project.end_projects(request.user))
    my_live_tasks = Task.objects.filter(contractor=request.user, complete_proc__lt=100).count
    my_end_tasks = Task.objects.filter(contractor=request.user, complete_proc__exact=100).count

    # how many time the project was carried out? EVERY project which I participated.
    projects_timedelta_chart = []
    for p in Project.objects.filter(complete_proc__exact=100).filter(owner=request.user):
        delta = p.enddate - p.startdate
        projects_timedelta_chart.append([p.name, delta.days])

    # Tasks order by months. Every task. Finished and not finished.
    tmp = Task.objects\
    					.filter(contractor=request.user)\
                        .annotate(month=TruncMonth('create_date'))\
                        .values('month')\
                        .annotate(c=Count('id'))
    tasks_month_count = month_order(tmp)

    data = {
            'projects_timedelta_chart': projects_timedelta_chart,
            'tasks_month_count': tasks_month_count,
            'live_projects_count': live_projects_count,
            'end_projects_count': end_projects_count,
            'my_live_tasks': my_live_tasks,
            'my_end_tasks': my_end_tasks,
            'default_password': check_password('password123', request.user.password)
    }
    return render(request, 'proman/index.html', data)

"""
Shows all projects
"""
@login_required(login_url='/login/')
def projects(request):
    user = request.user
    myprojects = Project.objects.filter(owner=user, complete_proc__lt=100)  # my projects
    end_myprojects = Project.objects.filter(owner=user, complete_proc__exact=100)
    notmyprojects = [i for i in user.team_set.all() if i.project.complete_proc < 100]  # projects which i participate
    end_notmyprojects = [i for i in user.team_set.all() if i.project.complete_proc == 100]
    end_projects = list(end_myprojects) + list(end_notmyprojects)
    data = {'myprojects': myprojects,
            'notmyprojects': notmyprojects,
            'end_projects': end_projects
            }
    return render(request, 'proman/projects.html', data)

"""
Shows form to add project
"""
@login_required(login_url='/login/')
def project_add(request):
    if request.method == 'POST':
        form = ProjectAddForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            startdate = form.cleaned_data['startdate']
            enddate = form.cleaned_data['enddate']
            Project.objects.create(name=name, owner=request.user, startdate=startdate,
                                   enddate=enddate, passforjoin=User.objects.make_random_password())
            return redirect('proman:projects')
    else:
        form = ProjectAddForm()
        return render(request, 'proman/project_add.html', {'form': form})

"""
Method to remove project
"""
@login_required(login_url='/login/')
def project_remove(request, project_id):
    project = get_object_or_404(Project, pk=project_id)
    if project.owner == request.user:
        project.delete()
    return redirect('proman:projects')

"""
Shows form to edit project
"""
@login_required(login_url='/login/')
def project_edit(request, project_id):
    project = get_object_or_404(Project, pk=project_id)
    if request.user != project.owner:
        return HttpResponseForbidden()
    form = ProjectAddForm(request.POST or None, instance=project)
    if request.method == 'POST' and form.is_valid():
        form.save()
        return redirect('proman:projects')
    else:
        return render(request, 'proman/project_edit.html', {'form': form, 'project': project})

"""
Shows project page with details
"""
@login_required(login_url='/login/')
def project_show(request, project_id):
    user = request.user
    project = get_object_or_404(Project, pk=project_id)
    members = project.team_set.all()
    proj_tasks = project.task_set.all()
    project.refresh_complete_proc(proj_tasks)
    if project.owner == user:  # owner
        data = {
                'owner': True,
                'project': project,
                'members': members,
                'tasks': proj_tasks,
                'level': project.complete_proc
        }
        return render(request, 'proman/project_show.html', data)
    else:
        if Team.objects.filter(project=project, member=user).exists():
            data = {
                'owner': False,
                'project': project,
                'members': members,
                'tasks': proj_tasks,
                'level': project.complete_proc
            }
            return render(request, 'proman/project_show.html', data)
        else:
            # user not in members
            return HttpResponseForbidden()

"""
Shows form to join to project. User sign in to project himself.
"""
@login_required(login_url='/login/')
def project_join(request):
    user = request.user
    if request.method == 'POST':
        form = ProjectJoinForm(request.POST)
        if form.is_valid():
            jointext = form.cleaned_data["passforjoin"]
            try:
                proj_id = int(jointext.split("_")[0])
                proj_password = jointext.split("_")[1]
            except ValueError:
                error = "Błędny kod dostępu !"
                form = ProjectJoinForm()
                data = {
                    'error': error,
                    'form': form
                    }
                return render(request, 'proman/project_join.html', data)

            project = get_object_or_404(Project, pk=proj_id)
            if project.passforjoin == proj_password:
                Team.objects.create(project=project, member=user)
                return redirect('proman:projects')
            else:
                error = "Błędny kod dostępu !"
                form = ProjectJoinForm()
                data = {
                    'error': error,
                    'form': form
                    }
                return render(request, 'proman/project_join.html', data)
    else:
        form = ProjectJoinForm()
        data = {
                'form': form
                }
        return render(request, 'proman/project_join.html', data)

"""
Method to delete user from project
"""
@login_required(login_url='/login/')
def project_del_member(request, project_id, member_id):
    project = get_object_or_404(Project, pk=project_id)
    if project.owner == request.user:
        member = get_object_or_404(User, pk=member_id)
        membership = Team.objects.get(project=project, member=member)
        if membership:
            membership.delete()
    return redirect('proman:project_show', project_id)

"""
Shows form to add user to project. Owner joins other users
"""
@login_required(login_url='/login/')
def project_add_member(request, project_id, member_id=None):
    project = get_object_or_404(Project, pk=project_id)
    if member_id:
        if project.owner == request.user:
            member = get_object_or_404(User, pk=member_id)
            Team.objects.create(project=project, member=member)
            return redirect('proman:project_add_member', project_id)
    else:
        t = project.team_set.all()
        tlist = [i.member.id for i in t]  # id list of members of project
        tlist.append(project.owner.id)  # add owner id to list
        restusers = User.objects.exclude(id__in=tlist).order_by('username')  # queryset of the rest of Users
        data = {
                'project': project,
                'restusers': restusers
            }
        return render(request, 'proman/project_add_member.html', data)

"""
Shows form to send a message between users.
"""
@login_required(login_url='/login/')
def message_send(request):
    user = request.user
    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            recipient = get_object_or_404(User, username=form.cleaned_data["recipient"])
            msg = form.cleaned_data["content"]
            Inbox.send_message(user, recipient, msg)
            success = "Wiadomość wysłana"
            form = MessageForm()  # clear Form
            data = {'form': form,
                    'success': success}
            return render(request, 'proman/message_send.html', data)
        else:
            form = MessageForm()  # clear Form
            error = "Nie udało się wysłać wiadomości"
            data = {'form': form,
                    'error': error}
            return render(request, 'proman/message_send.html', data)
    else:
        form = MessageForm()

proman/templates/proman/base.html
<!DOCTYPE html>
<html lang="pl-PL">
<style>
.chat_td_timestamp {
    font-size: 10px;
    float: right;
}
.chat_td_message {
    width: 85%;
    vertical-align: top;
}
.chat_td_user {
    vertical-align: top;
    font-weight: bold;
}
.chat_table {
    width: 100%;
    border-collapse: separate;
    border-spacing: 0 10px;
}
.chat_tr {
}
</style>
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Ubuntu" />
    <link href="https://fonts.googleapis.com/css?family=Bungee" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:600" rel="stylesheet">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    {% load static %}
    <link href="{% static 'proman/css/dashboard.css' %}" rel="stylesheet">

    {% block js_css_lib %}
    {% endblock %}

    <title>Simple Project Manager</title>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">Simple Project Manager</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'proman:user_profile' request.user.id %}">
                    {{ request.user }}
                </a></li>
                <li><a href="/login/logout/">Wyloguj</a></li>
              </ul>
            </div>
        </div>
    </nav>

    <div class="container-fluid">
          <div class="row">
              <div class="col-sm-3 col-md-2 sidebar">
                  <ul class="nav nav-sidebar">
                        {% if request.get_full_path == "/" %}<li class="active">{% else %}<li>{% endif %}
                            <a href="{% url 'proman:index' %}">Strona główna<span class="sr-only">(current)</span></a></li>

                        {% if request.get_full_path == "/projekty/" %}<li class="active">{% else %}<li>{% endif %}
                            <a href="{% url 'proman:projects' %}">Projekty</a></li>

                        {% if request.get_full_path == "/zadania/" %}<li class="active">{% else %}<li>{% endif %}
                            <a href="{% url 'proman:tasks' %}">Zadania</a></li>

                        {% if request.get_full_path == "/czat/" %}<li class="active">{% else %}<li>{% endif %}
                            <a href="{% url 'shoutbox:index' %}">Czat</a></li>
                  </ul>
              <hr>
              <div class="panel panel-primary">
                  <div class="panel-heading">
                      <h3 class="panel-title">
                          <a href="{% url 'proman:message_show' %}">
                            Wiadomości  <span class="glyphicon glyphicon-envelope" style="float: right" aria-hidden="true"></span>
                          </a>
                      </h3>
                  </div>
                  <div class="panel-body"> <!-- MESSAGES FROM USERS -->
                        {% for i in msgs %}
                            <b>{{ i.sender }}</b>:<br />{{ i.content|truncatechars:40 }}
                        {% endfor %}
                  </div>
              </div>
                  <a class="btn btn-success" href="{% url 'proman:message_send' %}">Wyślij wiadomość</a>
              </div>
              <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">

                  <div class="table-responsive">
                        {% block actions %}
                        {% endblock %}
                        {% block projects %}
                        {% endblock %}

                  </div>
              </div>
          </div>
    </div>
</body>
</html>

proman/templates/proman/message_send.html
{% extends 'proman/base.html' %}

{% load bootstrap %}
{% block projects %}
     {% if success %}
        <div class="alert alert-success" role="alert">{{ success }}</div>
    {% endif %}
    {% if error %}
        <div class="alert alert-danger" role="alert">{{ error }}</div>
    {% endif %}

    <div class="page-header"><h1>Wyślij wiadomość</h1></div>
    <form action="{% url 'proman:message_send' %}" method="post">
        {% csrf_token %}
        <div style="width: 20%">{{ form.recipient|bootstrap }}</div>
        <div style="width: 50%">{{ form.content|bootstrap }}</div>
        <input class="btn btn-success" type="submit" value="Wyślij" />
    </form>

{% endblock %}

{% block actions %}

{% endblock %}

proman/templates/proman/project_add.html
{% extends 'proman/base.html' %}

{% block js_css_lib %}
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
    <script>
        $(document).ready(function() {
            $('.datepicker').datepicker({
                dateFormat: "dd.mm.yy"
            });
        });
    </script>
{% endblock %}

{% load bootstrap %}
{% block projects %}
    <div class="page-header"><h1>Dodaj projekt</h1></div>
    <form action="{% url 'proman:project_add' %}" method="post">
        {% csrf_token %}
        <div style="width: 30%">{{ form.name|bootstrap }}</div>
        <div style="width: 12%">{{ form.startdate|bootstrap }}</div>
        <div style="width: 12%">{{ form.enddate|bootstrap }}</div>
        <input class="btn btn-success" type="submit" value="Dodaj" />
    </form>
{% endblock %}

proman/templates/proman/project_join.html
{% extends 'proman/base.html' %}

{% load bootstrap %}
{% block projects %}
    <div class="page-header"><h1>Dołącz do projektu</h1></div>
    <form action="{% url 'proman:project_join' %}" method="post">
        {% csrf_token %}
        <div style="width: 20%">{{ form|bootstrap }}</div>
        <input class="btn btn-success" type="submit" value="Dołącz" />
    </form>
    {% if error %}
        <br />
        <div class="alert alert-danger" role="alert">{{ error }}</div>
    {% endif %}
{% endblock %}

{% block actions %}

{% endblock %}

proman/templates/proman/project_show.html
{% extends 'proman/base.html' %}

{% block projects %}
    {% if owner %}
        <div class="page-header"><h1>{{ project.name }} <h4>właściciel: Ty<span style="float: right;">kod dostępu: {{ project.id }}_{{ project.passforjoin }}</span></h4></h1></div>
        <!-- left side -->
        <div class="col-md-6">
            <div class="panel panel-primary">
                  <div class="panel-heading"><h3 class="panel-title">Data zakończenia</h3></div>
                  <div class="panel-body">
                    {{ project.enddate }} (pozostało {{ project.enddate|timeuntil }})
                  </div>
            </div>

            <div class="panel panel-primary">
                  <div class="panel-heading"><h3 class="panel-title">Zespół ({{ members.count }})</h3></div>
                  <div class="panel-body">
                    <div class="list-group">
                        {% for member in members %}
                            <span class="list-group-item">
                                <a href="{% url 'proman:user_profile' member.member.id %}">{{ member.member }}</a>
                                <a href="{% url 'proman:project_del_member' project.id member.member.id %}" style="float: right"><span class="glyphicon glyphicon-minus" aria-hidden="true"></span> Usuń</a>
                            </span>
                        {% endfor %}
                    </div>
                  </div>
            </div>
        </div>
        <!-- right side -->
        <div class="col-md-6">
            <div class="panel panel-primary">
                  <div class="panel-heading"><h3 class="panel-title">Postęp</h3></div>
                    <div class="panel-body">
                        <div class="progress">
                            <div class="progress-bar" role="progressbar" aria-valuenow="{{ level|floatformat }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ level|floatformat:"0" }}%">
                                {{ level|floatformat }}%
                            </div>
                        </div>
                    </div>
            </div>

            <div class="panel panel-primary">
                  <div class="panel-heading"><h3 class="panel-title">Zadania ({{ tasks.count }})</h3></div>
                    <div class="panel-body">
                        <div class="list-group">
                        {% for task in tasks %}
                            <a href="{% url 'proman:task_show' task.id %}" class="list-group-item">({{ task.contractor }}) <b>{{ task.name }}:</b> {{ task.description|truncatechars:60 }}</a>
                        {% endfor %}
                        </div>
                    </div>
            </div>
        </div>

    {% else %}

        <div class="page-header"><h1>{{ project.name }} <h4>właściciel: {{ project.owner }}</h4></h1></div>
        <!-- left side -->
        <div class="col-md-6">
            <div class="panel panel-primary">
                  <div class="panel-heading"><h3 class="panel-title">Data zakończenia</h3></div>
                  <div class="panel-body">
                    {{ project.enddate }} (pozostało {{ project.enddate|timeuntil }})
                  </div>
            </div>

            <div class="panel panel-primary">
                  <div class="panel-heading"><h3 class="panel-title">Zespół ({{ members.count }})</h3></div>
                  <div class="panel-body">
                    <div class="list-group">
                        {% for member in members %}
                            <a href="{% url 'proman:user_profile' member.member.id %}" class="list-group-item">{{ member.member }}</a>
                        {% endfor %}
                    </div>
                  </div>
            </div>
        </div>
        <!-- right side -->
        <div class="col-md-6">
            <div class="panel panel-primary">
                  <div class="panel-heading"><h3 class="panel-title">Postęp</h3></div>
                    <div class="panel-body">
                        <div class="progress">
                            <div class="progress-bar" role="progressbar" aria-valuenow="{{ level|floatformat }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ level|floatformat:"0" }}%">
                                {{ level|floatformat }}%
                            </div>
                        </div>
                    </div>
            </div>

            <div class="panel panel-primary">
                  <div class="panel-heading"><h3 class="panel-title">Zadania ({{ tasks.count }})</h3></div>
                    <div class="panel-body">
                        <div class="list-group">
                        {% for task in tasks %}
                            <a href="{% url 'proman:task_show' task.id %}" class="list-group-item">({{ task.contractor }}) <b>{{ task.name }}:</b> {{ task.description|truncatechars:60 }}</a>
                        {% endfor %}
                    </div>
                    </div>
            </div>
        </div>
    {% endif %}

{% endblock %}

{% block actions %}
    {% if owner and project.complete_proc < 100 %}
    <a href="{% url 'proman:project_add_member' project.id %}" class="btn btn-primary btn-sm">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Uczestnik</a>

    <a href="{% url 'proman:task_add' project.id %}" class="btn btn-primary btn-sm">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Zadanie</a>

    <a href="{% url 'proman:project_edit' project.id %}" class="btn btn-success btn-sm">
        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Edytuj</a>

    <a href="{% url 'proman:task_change_weight' project.id %}" class="btn btn-success btn-sm">
        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Zmień wagi</a>

    <a href="{% url 'proman:project_remove' project.id %}" class="btn btn-danger btn-sm">
        <span class="glyphicon glyphicon-minus" aria-hidden="true"></span> Usuń</a>
    {% endif %}
    {% if project.complete_proc == 100 %}
        <div class="alert alert-info">
            Projekt zakończony
        </div>
    {% endif %}
{% endblock %}