login_app/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

from . import views

app_name = 'login_app'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/', auth_views.login, {'template_name': 'login_app/login.html'}, name='login'),
    url(r'^logout/', auth_views.logout, name='logout')
]

proman/urls.py
from django.conf.urls import url
from . import views

app_name = 'proman'
urlpatterns = [
    url(r'^$', views.index, name='index'),

    url(r'^wiadomosc/wyslij/$', views.message_send, name='message_send'),
    url(r'^wiadomosci/$', views.message_show, name='message_show'),
    url(r'^wiadomosci/(?P<friend_id>[0-9]+)/$', views.message_show, name='message_show'),

    url(r'^profile/(?P<user_id>[0-9]+)/$', views.user_profile, name='user_profile'),

    url(r'^projekty/$', views.projects, name='projects'),
    url(r'^projekty/edytuj/(?P<project_id>[0-9]+)/$', views.project_edit, name='project_edit'),
    url(r'^projekty/usun/(?P<project_id>[0-9]+)/$', views.project_remove, name='project_remove'),
    url(r'^projekty/przegladaj/(?P<project_id>[0-9]+)/$', views.project_show, name='project_show'),
    url(r'^projekty/dodaj/$', views.project_add, name='project_add'),

    url(r'^projekty/dolacz/$', views.project_join, name='project_join'),  # form with Access Code. User joins himself
    url(r'^projekty/dolacz/(?P<project_id>[0-9]+)/$',
        views.project_add_member, name='project_add_member'),  # owner joins others
    url(r'^projekty/dolacz/(?P<project_id>[0-9]+)/(?P<member_id>[0-9]*)/$',
        views.project_add_member, name='project_add_member'),  # owner joins others
    url(r'^projekty/odlacz/(?P<project_id>[0-9]+)/(?P<member_id>[0-9]+)/$',
        views.project_del_member, name='project_del_member'),
    url(r'^projekty/wagi/(?P<project_id>[0-9]+)/$', views.task_change_weight, name='task_change_weight'),

    url(r'^zadania/$', views.tasks, name='tasks'),
    url(r'^zadanie/przegladaj/(?P<task_id>[0-9]+)/$', views.task_show, name="task_show"),
    url(r'^zadanie/dodaj/(?P<project_id>[0-9]+)/$', views.task_add, name="task_add"),
    url(r'^zadanie/usun/(?P<task_id>[0-9]+)/$', views.task_remove, name='task_remove'),
    url(r'^zadanie/edytuj/(?P<task_id>[0-9]+)/$', views.task_edit, name='task_edit'),
    url(r'^zadanie/zrobione/(?P<task_id>[0-9]+)/$', views.task_done, name='task_done'),

]

simpleprojectmanager/urls.py
from django.conf.urls import url, include
from django.contrib import admin
# from django.views.static import serve

urlpatterns = [
    url(r'^', include('proman.urls'), name='proman'),
    url(r'^login/', include('login_app.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^czat/', include('shoutbox.urls'), name='shoutbox'),
    # url(r'^static/', serve),
]

login_app/models.py
from django.db import models

# Create your models here.

login_app/views.py
from django.shortcuts import render
from django.http import HttpResponse

from django.contrib.auth import authenticate, login # authenticate user


def index(request):
    return render(request, 'login_app/login.html')

def login(request):
    username = request.POST.get('username')
    password = request.POST.get('password')
    user = authenticate(username=username, password=password)
    if user is not None:
        login(request, user)

login_app/templates/login_app/login.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Ubuntu" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    {% load static %}
    <link href="{% static 'login_app/css/signin.css' %}" rel="stylesheet">

    <title>{% block title %}Logowanie{% endblock %}</title>
</head>
<body>
  <div class="container">
        {% if not user.is_authenticated %}
          <form class="form-signin" action="{% url 'login_app:login' %}" method="post">
            <h2 class="form-signin-heading">Zaloguj się</h2>
            {% csrf_token %}
            <label for="username" class="sr-only"><b>Username</b></label>
            <input type="text" class="form-control" placeholder="Enter Username" name="username" required>
            <label for="password" class="sr-only"><b>Password</b></label>
            <input type="password" class="form-control" placeholder="Enter Password" name="password" required>
            <button class="btn btn-lg btn-primary btn-block" type="submit">Login</button>
          </form>
        {% else %}
            <div class="container-fluid" style="padding: 3% 0% 0% 3%; font-size: 25px">
                Chcesz się <a href={% url 'login_app:logout' %}> wylogować</a>?
            </div>
        {% endif %}
        {% if error %}
            {{ error }}
        {% endif %}
  </div>
</body>
</html>